default:
  image: node:latest
  before_script:
    - cd smitenoobleague-web-app

# This folder is cached between builds
cache:
  paths:
    - node_modules/

stages:
    - test

test:
  script:
    - npm test
