name: Deploy containerized back-end to DO

on:
  push:
    branches: 
      - master
    paths:
      - smitenoobleague-microservices/**
  pull_request:     
    branches: 
      - master
    paths:
      - smitenoobleague-microservices/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: copy files via sshkey
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        passphrase: ${{ secrets.SSHPASS }}
        port: ${{ secrets.PORT }}
        source: "./smitenoobleague-microservices/*"
        target: "/opt/app/"

    - name: Executing remote  command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.SSHPASS }}
        key: ${{ secrets.SSHKEY }}
        script: |
          cd /opt/app
          docker-compose -f docker-compose.yml up -d