# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Next.js app to DigitalOcean

on:
  release:
    types: [created]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
      working-directory: smitenoobleague-web-app
    - name: Build
      run: npm run build --if-present
      working-directory: smitenoobleague-web-app
       
    - name: Test
      run: npm test
      working-directory: smitenoobleague-web-app
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Create deployment to the app platform.
      run: doctl apps create-deployment ${{ secrets.DO_APP_ID }} 