name: Back-end .NET Core CI


#   push:
#     branches: 
#       - master
#     paths:
#       - smitenoobleague-microservices/**

on:
  push:
    branches: 
      - dev
    paths:
      - smitenoobleague-microservices/**
  pull_request:     
    branches: 
      - master
    paths:
      - smitenoobleague-microservices/**

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: |
        cd smitenoobleague-microservices 
        dotnet smitenoobleague-microservices.sln
    - name: Build
      run: |
        cd smitenoobleague-microservices
        dotnet build --configuration Release --no-restore smitenoobleague-microservices.sln
    - name: Test
      run: |
        cd smitenoobleague-microservices
        dotnet test smitenoobleague-microservices.sln
